# Generated by Django 5.2.8 on 2026-02-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packing_lists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packingitem",
            old_name="packing_lists",
            new_name="packing_list",
        ),
    ]
