# Generated by Django 5.2.8 on 2026-02-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packing_lists", "0002_rename_packing_lists_packingitem_packing_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packingitemtemplate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="packing_lists.packinglisttemplate",
            ),
        ),
    ]
