# Generated by Django 5.2.8 on 2026-03-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("member_added", "Member added"),
                    ("member_removed", "Member removed"),
                    ("member_left", "Member left"),
                    ("invite_sent", "Invite sent"),
                ],
                max_length=50,
            ),
        ),
    ]
