# Generated by Django 5.2.8 on 2026-03-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
    ]
