# Generated by Django 5.2.8 on 2026-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="note_type",
            field=models.CharField(
                choices=[("private", "Private"), ("shared", "Shared")],
                default="private",
                max_length=10,
            ),
        ),
    ]
