# Generated by Django 5.2.8 on 2026-02-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default.jpg",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
