# Generated by Django 5.2.8 on 2025-12-11 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_alter_tripmember_status_alter_tripmember_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="participants",
        ),
        migrations.AlterUniqueTogether(
            name="tripmember",
            unique_together={("trip", "user")},
        ),
        migrations.RemoveField(
            model_name="tripmember",
            name="status",
        ),
    ]
