# Generated by Django 5.2.8 on 2026-08-11 13:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_alter_tripinvite_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
